 
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: diet-planner-v6_development
 
test:
  <<: *default
  database: diet-planner-v6_test
 
production:
  <<: *default
  database: diet-planner-v6_production
  username: diet-planner-v6
  password: <%= ENV['SWT-V3_DATABASE_PASSWORD'] %>
