
require 'pry'



FOODS = [
["Alcohol", "Beer, 12 fl. oz.", 145],
["Alcohol", "Beer, light, 12 fl. oz.", 100],
["Alcohol", "Liquor, 100 proof, 1 fl. oz.", 83],
["Alcohol", "Liquor, 80 proof, 1 fl. oz.", 65],
["Alcohol", "Liquor, 86 proof, 1 fl. oz.", 70],
["Alcohol", "Liquor, 90 proof, 1 fl. oz.", 74],
["Alcohol", "Wine, 4 fl. oz.", 100],
["Arby's", "Beef n Cheddar, each", 455],
["Arby's", "Chicken breast, each", 493],
["Arby's", "Chicken club, each", 610],
["Arby's", "French fries, 2 1/2 oz.", 246],
["Arby's", "Ham n Cheese, each", 292],
["Arby's", "Jamocha shake, 11 1/2 fl. oz.", 326],
["Arby's", "Potato cakes, 1 serving", 204],
["Arby's", "Roast beef, each", 353],
["Arby's", "Super Roast Beef, each", 501],
["Arby's", "Turkey deluxe, each", 375],
["Beverages", "Bouillon, beef or chicken, instant, 1 tsp.", 2],
["Beverages", "Bouillon, beef or chicken, 1 cube", 4],
["Beverages", "Coca-Cola Classic, 12 fl. oz.", 144],
["Beverages", "Coca-Cola, New, 12 fl. oz.", 154],
["Beverages", "Coffee, 1 cup", 2],
["Beverages", "Coffee, Cafe Vienna, General Foods—6 fl. oz.", 30],
["Beverages", "Diet Coke, 12 fl. oz.", 1],
["Beverages", "Diet Pepsi, 12 fl. oz.", 1],
["Beverages", "Sprite, 12 fl. oz.", 142],
["Bread", "Bagel, Sara Lee Deli style", 230],
["Bread", "Bagel, plain, each", 150],
["Bread", "Biscuit, home recipe—2 in.", 108],
["Bread", "Blueberry muffin, 1 muffin", 112],
["Bread", "Bread cubes, 1 cup", 111],
["Bread", "Bread stuffing, dry, crumbly—1 cup", 501],
["Bread", "Bread, rye, 1 slice", 61],
["Bread", "Bread, white, 1 slice", 68],
["Bread", "Bread, whole wheat, 1 slice", 67],
["Bread", "Brown and serve roll, 1 roll", 84],
["Bread", "Bun, hamburger, each", 119],
["Bread", "Bun, hot dog, each", 119],
["Bread", "Butter Tastin' Biscuit, 1869 Brand, each", 100],
["Bread", "Buttermilk biscuit, fluffy, Hungry Jack, each", 90],
["Bread", "Cornbread muffin, 1 muffin, home recipe", 126],
["Bread", "Cornbread twists, 1 stick—Pillsbury", 70],
["Bread", "Cornbread, from mix, 1/9 of 12 oz. mix, 1 egg, milk", 178],
["Bread", "Crescent roll, 1 roll—Pillsbury", 100],
["Bread", "Croissant, each", 200],
["Bread", "Croutons, seasoned, 1/2 oz—Pepperidge Farm", 70],
["Bread", "Dinner roll, cloverleaf or pan roll", 83],
["Bread", "Eggo blueberry waffles, each", 130],
["Bread", "Eggo buttermilk waffles, each", 120],
["Bread", "Eggo oat bran waffles, each", 110],
["Bread", "English muffin, Thomas', 1 muffin", 130],
["Bread", "French bread, 1 slice", 73],
["Bread", "Hoagie roll, 11 1/2 x 3 in.", 392],
["Bread", "Lite bread, 1 slice—Merita lite wheat", 40],
["Bread", "Lite pancake mix, 4 in. pancake—Aunt Jemima", 43],
["Bread", "Oat bran muffin, 1 muffin—Duncan Hines", 110],
["Bread", "Onion roll, Pepperidge Farm, each", 150],
["Bread", "Pancake mix, 4 in. pancake—Aunt Jemima", 83],
["Bread", "Pancakes, home recipe, 1 4 in. cake", 62],
["Bread", "Pancakes, home recipe, 1 6 in. cake", 169],
["Bread", "Pillsbury buttermilk biscuit, 1 biscuit", 50],
["Bread", "Pita bread, 1/2 round bread, Mediterranean", 80],
["Bread", "Taco shells, 1 shell—Old El Paso", 55],
["Burger King", "Bleu Cheese dressing, 1 packet", 300],
["Burger King", "Cheese Whopper, each", 711],
["Burger King", "Chef salad, each", 180],
["Burger King", "Chicken salad, each", 140],
["Burger King", "Chicken specialty, each", 688],
["Burger King", "Chicken Tenders, 1 piece", 34],
["Burger King", "Croissan'wich, Ham, egg and cheese", 335],
["Burger King", "Croissan'wich, Bacon, egg and cheese", 355],
["Burger King", "Croissan'wich, Sausage, egg and cheese", 538],
["Burger King", "French dressing, 1 packet", 280],
["Burger King", "French fries, 1 serving", 227],
["Burger King", "Garden salad, each", 90],
["Burger King", "House dressing, 1 packet", 260],
["Burger King", "Onion rings, 1 serving", 274],
["Burger King", "Reduced Italian dressing, 1 packet", 30],
["Burger King", "Salad bacon bits, 1 packet", 16],
["Burger King", "Salad croutons, 1 packet", 29],
["Burger King", "Thousand Island, 1 packet", 240],
["Burger King", "Vanilla milkshake, regular", 321],
["Burger King", "Whaler, each", 488],
["Burger King", "Whopper, each", 628],
["Candy", "5th Avenue Bar, each", 270],
["Candy", "Bar None, each", 240],
["Candy", "Chocolate Caramel Figurine Bar, each", 100],
["Candy", "Chocolate Figurine Diet Bar, each", 100],
["Candy", "Figurine, Peanut Butter Chocolate, each", 100],
["Candy", "Fruit Roll-Ups, 1/2 oz. roll", 50],
["Candy", "Granola bar, Nature Valley, each, Oats 'n Honey", 120],
["Candy", "Granola bar, Nature Valley, each, peanut butter", 120],
["Candy", "Halvah, 1 oz. bar", 160],
["Candy", "Hershey bar with almonds, each", 250],
["Candy", "Hershey chocolate bar, each", 250],
["Candy", "Hershey's Kisses, 9 pieces", 220],
["Candy", "Hershey's Mr. Goodbar, each 1 3/4 oz.", 300],
["Candy", "Hershey's Symphony chocolate, Almonds & Toffee Chips", 220],
["Candy", "Kit Kat bar, each", 250],
["Candy", "Krackel bar, each", 250],
["Candy", "Kudos, chocolate chip, 1 granola bar", 180],
["Candy", "M&Ms, peanut, 1 package", 250],
["Candy", "M&Ms, plain, 1 package", 240],
["Candy", "Mars bar, each", 240],
["Candy", "Marshmallow, 1 large", 23],
["Candy", "Peanut butter cups, Reese's—2 cups", 280],
["Candy", "Reese's Pieces, 1 package, 1.95 oz.", 270],
["Candy", "Rolo caramels, 9 pieces", 270],
["Candy", "S'Mores Figurine Diet Bar, each", 100],
["Candy", "Skor Toffee bar, each", 220],
["Candy", "Snickers, each", 275],
["Candy", "Twix candy bar, 1 package, 2 bars", 280],
["Candy", "Vanilla Figurine Diet Bar, each", 100],
["Candy", "Whatchamacallit candy bar, each", 260],
["Cereal", "Cheerios, 1 oz. or 1 1/4 cups", 110],
["Cereal", "Cracklin' Oat Bran, 1 oz. or 1/2 cup", 110],
["Cereal", "Honey Bunches of Oats, Post cereal—2/3 cup", 110],
["Cereal", "Kelfoodg's Corn Flakes, 1 oz. or 1 cup", 100],
["Cereal", "Kelfoodg's Crispix, 1 oz. or 1 cup", 110],
["Cereal", "Kelfoodg's Frosted Flakes, 1 oz. or 3/4 cup", 110],
["Cereal", "Kelfoodg's Heartwise, 1 oz. or 2/3 cup", 90],
["Cereal", "Kelfoodg's Product 19, 1 oz. or 1 cup", 100],
["Cereal", "Kelfoodg's Raisin Bran, 1 oz. or 3/4 cup", 120],
["Cereal", "Kelfoodg's Special K, 1 oz. or 1 cup", 110],
["Cereal", "Mueslix Crispy Blend, 1 oz. or 2/3 cup", 160],
["Cereal", "Mueslix Golden Crunch, 1 oz. or 1/2 cup", 120],
["Cereal", "Nature Valley cereal, toasted oat—1 cup", 390],
["Cereal", "Nut & Honey Crunch, 1 oz. or 2/3 cup", 110],
["Cereal", "Oatmeal, cooked, 1 cup", 132],
["Cereal", "Oatmeal, dry, 1 cup", 312],
["Cereal", "Rice Chex, 1 oz., or 1 1/8 cup", 110],
["Cereal", "Rice Krispies, 1 oz. or 1 cup", 110],
["Cereal", "Shredded wheat, regular, 1 biscuit", 80],
["Cereal", "Shredded Wheat Squares, Fruit—1 oz. or 1/2 cup", 90],
["Cereal", "Spoonsize shredded wheat, 1 cup", 165],
["Cereal", "Total cereal, 1 oz. or 1 cup", 100],
["Cereal", "Trix cereal, 1 oz. or 1 cup", 110],
["Cereal", "Wheat Chex, 1 oz.", 100],
["Cereal", "Wheaties, 1 oz. or 1 cup", 100],
["Cookies", "Butter cookies, 1 Danish butter cookie", 23],
["Cookies", "Chocolate chip cookie, home recipe", 51],
["Cookies", "Chocolate chip cookies, Girl Scout Country Hearth", 35],
["Cookies", "Chocolate chip cookies, Entenmann's", 49],
["Cookies", "Fig newtons, Lance, 1 package", 150],
["Cookies", "Girl Scout cookies, Trefoils—shortbread", 30],
["Cookies", "Girl Scout cookies, Country Hearth Choc Chip", 35],
["Cookies", "Girl Scout cookies, Thin Mints", 40],
["Cookies", "Girl Scout cookies, Do-si-dos p'nut butter", 50],
["Cookies", "Girl scout cookies, Cabana cremes", 60],
["Cookies", "Girl Scout cookies, Tagalongs—peanut butter", 80],
["Cookies", "Girl Scout Samoas, coconut cookie", 80],
["Cookies", "Nekot, Lance p'nut butter cookies", 210],
["Cookies", "Oatmeal cookie, 1 2 5/8 in. cookie", 59],
["Cookies", "Oatmeal raisin cookies, Entenmann's", 49],
["Cookies", "Oreos, each", 50],
["Cookies", "Pecan Sandy, each", 80],
["Cookies", "Sugar cookie, home recipe—2 1/4 in.", 36],
["Cookies", "Vanilla wafers cookies, Keebler", 20],
["Crackers", "American Heritage sesame crackers, 4 crackers", 80],
["Crackers", "Bacon crackers, 1 cracker—Nabisco", 10],
["Crackers", "Cheese crackers, Lance Toastchee—6 crackers", 190],
["Crackers", "Cheese on wheat, Lance crackers, 1 package", 180],
["Crackers", "Goldfish crackers, original, 45 crackers", 140],
["Crackers", "Goldfish crackers, pretzel, 40 crackers", 120],
["Crackers", "Ritz crackers, 4 crackers", 70],
["Crackers", "Rye-chee crackers, 1 package—Lance", 190],
["Crackers", "Saltine crackers, each", 12],
["Crackers", "Sunshine American Heritage, 1 wheat bran cracker", 150],
["Crackers", "Sunshine Cheez-it crackers, 12 crackers, 1/2 oz.", 70],
["Crackers", "Thin Bits, 12 crackers", 70],
["Crackers", "Town House crackers, 4 crackers", 70],
["Crackers", "Triscuit, 3 wafers", 60],
["Crackers", "Van-O-Lunch, Lance, 6 crackers", 180],
["Crackers", "Vegetable Thins, Nabisco—7 crackers", 70],
["Crackers", "Waverly wafers, 4 crackers", 70],
["Crackers", "Wheat Bran crackers, Sunshine, 1 cracker", 15],
["Crackers", "Wheat Thins, 8 crackers", 70],
["Dairy", "Butter, 1 tbsp", 100],
["Dairy", "Butter, 1 pat", 36],
["Dairy", "Butter, stick, 4 oz.", 813],
["Dairy", "Buttermilk, low-fat, 1 cup", 90],
["Dairy", "Cheese, American, 1 slice, Kraft", 100],
["Dairy", "Cheese, American Lite, 1 slice", 70],
["Dairy", "Cheese, Brie, 1 oz.", 95],
["Dairy", "Cheese, Camembert, 1 oz.", 85],
["Dairy", "Cheese, cheddar, 1 oz., or 1/4 cup shredded", 114],
["Dairy", "Cheese, colby, 1 oz.", 112],
["Dairy", "Cheese, gouda, 1 oz.", 101],
["Dairy", "Cheese, liver, 1 oz.", 86],
["Dairy", "Cheese, Monterey jack, 1 oz.", 106],
["Dairy", "Cheese, mozarrella, skim, 1 oz., partly skim milk", 79],
["Dairy", "Cheese, mozzarella, 1 oz., or 1/4 cup shredded", 90],
["Dairy", "Cheese, muenster, 1 oz.", 104],
["Dairy", "Cheese, Parmesan, grated, 1 tbsp.", 23],
["Dairy", "Cheese, Parmesan, grated, 1 oz.", 129],
["Dairy", "Cheese, pimento, 1 oz.", 106],
["Dairy", "Cheese, provolone, 1 oz.", 100],
["Dairy", "Cheese, ricotta, 1 oz., part-skim", 35],
["Dairy", "Cheese, Swiss, 1 oz.", 107],
["Dairy", "Cheese, Swiss slices, 1 1/4 oz. 7 1/2 x 4 in. slice", 130],
["Dairy", "Cottage cheese, 1pct fat, 1 cup", 164],
["Dairy", "Cottage cheese, 2pct fat, 1 cup", 203],
["Dairy", "Cottage cheese, creamed, 1 cup", 217],
["Dairy", "Cottage cheese, dry curd, 1 cup", 123],
["Dairy", "Cream cheese, 1 oz.", 414],
["Dairy", "Cream cheese, light, Kraft—1 oz., 2 tbsp.", 60],
["Dairy", "Cream, light, 1 tbsp.", 29],
["Dairy", "Cream, light, 1 cup", 469],
["Dairy", "Egg nog, 1 cup", 342],
["Dairy", "Half and half, 1 tbsp.", 20],
["Dairy", "Half and half, 1 cup", 315],
["Dairy", "Ice cream, vanilla, hard, 1 cup", 269],
["Dairy", "Ice cream, vanilla, soft, 1 cup", 377],
["Dairy", "Ice cream, 'death by Chocolate', 1 cup", 500],
["Dairy", "Ice milk, vanilla, hard, 1 cup", 184],
["Dairy", "Ice milk, vanilla, soft, 1 cup", 223],
["Dairy", "Imitation sour cream, 1 tbsp.—Light Choice", 25],
["Dairy", "Margarine, 1 tbsp.", 102],
["Dairy", "Margarine, 1 stick", 816],
["Dairy", "Milk, low fat, 8 fl. oz., 1pct fat", 102],
["Dairy", "Milk, low fat, 8 fl. oz., 2pct fat", 121],
["Dairy", "Milk, nonfat (skim), 8 fl. oz.", 86],
["Dairy", "Milk, whole, 8 fl. oz. 3.3pct fat", 150],
["Dairy", "Non-dairy creamer, 1 tsp.", 11],
["Dairy", "Soft margarine, 1 tbsp.—Fleishmann", 100],
["Dairy", "Sour cream, 1 tbsp.", 26],
["Dairy", "Sour cream, 1 cup", 493],
["Dairy", "Squeeze cheese, 1 oz.", 82],
["Dairy", "Velveeta cheese, 1 oz.", 80],
["Dairy", "Velveeta cheese slices, 3/4 oz. slice", 68],
["Dairy", "Whipped cream, 1 cup, canned pressurised", 154],
["Dairy", "Whipping cream, heavy, 1 cup, whipped", 410],
["Dairy", "Whipping cream, light, 1 cup, whipped", 349],
["Dairy", "Yogurt, Weight Watchers", 150],
["Dairy", "Yogurt, Dannon plain, 1 cup", 140],
["Dairy", "Yogurt, Dannon vanilla, 8 oz.", 210],
["Dairy", "Yogurt, Dannon with fruit, 1 cup", 240],
["Dairy", "Yogurt, plain, 1 cup", 150],
["Dessert", "Angel food cake, 1/12 of 9 in. cake", 137],
["Dessert", "Apple pie, frozen, 1/6 of pie, Banquet", 250],
["Dessert", "Apple spice cake, 1 Hostess Light", 130],
["Dessert", "Banana cake, from mix, 1/12 cake—Pillsbury", 250],
["Dessert", "Blackout pudding cake, Entenmann's 1/12 of cake", 96],
["Dessert", "Blueberry crunch cake, Entenmann's 1/12 of cake", 113],
["Dessert", "Carrot 'n Spice cake, Pillsbury mix—1/12 cake", 260],
["Dessert", "Carrot cake, Entenmann's 1/12 of cake", 114],
["Dessert", "Cheese crumb Babka, Entenmann's 1/12 of cake", 105],
["Dessert", "Cherry pie, frozen, 1/6 pie, Banquet", 250],
["Dessert", "Chocolate cake, 1/12 of 2 layer cake", 308],
["Dessert", "Chocolate fudge, 1 cu. in.", 84],
["Dessert", "Chocolate pound cake, Entenmann's 1/12 of cake", 123],
["Dessert", "Cinnamon Raisin Danish, each, Pillsbury", 140],
["Dessert", "Cinnamon Roll, each, Pillsbury", 210],
["Dessert", "Coffee cake, apple raisin, Entenmann's 1/12 of cake", 90],
["Dessert", "Coffee cake, Bavarian creme, Entenmann's 1/12 of cake", 103],
["Dessert", "Coffee cake, cheese-filled, Entenmann's 1/12 of cake", 105],
["Dessert", "Coffee cake, cherry cheese, Entenmann's 1/12 of cake", 90],
["Dessert", "Crunch cake, banana walnut, Entenmann's 1/12 of cake", 123],
["Dessert", "Crystal Light popsicles, 1 diet frozen drink bar", 14],
["Dessert", "Devils food cake, 1/12 of 9 in. cake", 312],
["Dessert", "Double fudge cake, Entenmann's 1/12 of cake", 116],
["Dessert", "Fig Cake, Lance—2 1/8 oz.", 210],
["Dessert", "Frozen yogurt, peach, Sealtest fat-free, 1 cup", 200],
["Dessert", "Fudge brownie with walnuts, Pillsbury mix—2 in. square", 150],
["Dessert", "Fudge golden cake, Entenmann's 1/12 of cake", 116],
["Dessert", "Gingerbread cake, 1/9 of 8 x 8 in. cake", 174],
["Dessert", "Golden pound cake, Entenmann's 1/12 of cake", 98],
["Dessert", "Hershey's Fudge Topping, 1 tbsp.", 50],
["Dessert", "Hostess lights, 1 apple spice cake", 130],
["Dessert", "Iced cinnamon roll, Pillsbury", 110],
["Dessert", "Lemon twist, Entenmann's 1/12 of cake", 113],
["Dessert", "Oatmeal Cake, Lance—creme-filled", 240],
["Dessert", "Orange Danish, Pillsbury", 140],
["Dessert", "Orange sunshine cake, Entenmann's 1/12 of cake", 105],
["Dessert", "Peach pie, 1/8 pie", 301],
["Dessert", "Pecan pie, 1/8 of 9 in. pie", 431],
["Dessert", "Pumpkin pie, 1/8 pie", 241],
["Dessert", "Raspberry twist, Entenmann's 1/12 of cake", 113],
["Dessert", "Streusel coffee cake, Pillsbury, 1/8 of cake", 180],
["Dessert", "Twinkies, each", 160],
["Dessert", "White cake, 1/12 of 2 layer cake", 333],
["Dessert", "Yellow cake, 1/12 of 2 layer cake", 310],
["Domino's Pizza", "Cheese pizza, 1 slice, 16 in. pizza", 188],
["Domino's Pizza", "Deluxe pizza, 1 slice, 16 in. pizza", 299],
["Domino's Pizza", "Ham pizza, 1 slice, 16 in. pizza", 208],
["Domino's Pizza", "Pepperoni pizza, 1 slice, 16 in. pizza", 230],
["Domino's Pizza", "Pizza, double cheese, 1 slice, 16 in. pizza", 272],
["Domino's Pizza", "Pizza, sausage & mushroom, 1 slice, 16 oz. pizza", 215],
["Domino's Pizza", "Veggie pizza, 1 slice, 16 in. pizza", 249],
["Dressing", "Blue cheese dressing, 1 tbsp.", 77],
["Dressing", "Blue cheese dressing, 1 cup", 1235],
["Dressing", "Blue cheese, low fat, 1 tbsp.", 3],
["Dressing", "Blue cheese, low fat, 1 cup", 47],
["Dressing", "Italian dressing, 1 tbsp.", 69],
["Dressing", "Italian dressing, 1 cup", 1098],
["Dressing", "Oil and vinegar dressing, Newman's Own, 1 tbsp.", 81],
["Dressing", "Ranch fat free dressing, Kraft, 1 tbsp.", 16],
["Dressing", "Ranch salad dressing, Hidden Valley 1 tbsp.", 40],
["Dunkin' Donuts", "Apple filled donut, each", 250],
["Dunkin' Donuts", "Cake donut, each", 270],
["Dunkin' Donuts", "Chocolate croissant, each", 440],
["Dunkin' Donuts", "Chocolate frosted donut, each", 200],
["Dunkin' Donuts", "Croissant, each", 310],
["Dunkin' Donuts", "Donut, Bavarian creme-filled, each", 240],
["Dunkin' Donuts", "Glazed donut, each", 200],
["Dunkin' Donuts", "Glazed French cruller, each", 140],
["Dunkin' Donuts", "Jelly donut, each", 220],
["Dunkin' Donuts", "Oat bran muffin, each", 330],
["Eggs", "Egg white, 1 large egg white", 17],
["Eggs", "Egg yolk, from 1 large egg", 59],
["Eggs", "Egg, fried in butter, 1 large egg", 99],
["Eggs", "Egg, raw, boiled, or poached, 1 large", 82],
["Eggs", "Scrambled eggs, 1 egg with butter & milk", 111],
["Eggs", "Scrambled eggs, 1 cup, with butter & milk", 325],
["Fish", "Alaska King crab, 1 leg", 129],
["Fish", "Alaska King crab, steamed, 4 oz.", 109],
["Fish", "Blue crab, steamed, 1 cup or 4.8 oz.", 138],
["Fish", "Catfish, fried, 4 oz. fillet", 259],
["Fish", "Catfish, raw, 4 oz.", 132],
["Fish", "Clams, canned, 1 can", 112],
["Fish", "Crab cakes, 1 2 oz. cake", 93],
["Fish", "Crab meat, canned, 1 cup or 4.8 oz.", 133],
["Fish", "Crab, deviled, 1 cup", 451],
["Fish", "Crab, deviled, frozen, Mrs. Paul's—1 cake", 170],
["Fish", "Crayfish, steamed, 4 oz.", 129],
["Fish", "Croaker, fried, 4 oz.", 251],
["Fish", "Croaker, raw, 4 oz.", 119],
["Fish", "Dolphinfish, raw, 4 oz.", 97],
["Fish", "Eel, baked, 4 oz.", 267],
["Fish", "Fish sticks, Mrs. Paul's, 4 sticks", 200],
["Fish", "Fish, breaded and fried, 3 1/2 oz.", 250],
["Fish", "Fish, raw, broiled, poached, 3 1/2 oz.", 140],
["Fish", "Flounder, baked, 4 oz.", 132],
["Fish", "Flounder, fried, 2 fillets, Mrs. Paul's", 270],
["Fish", "Halibut, broiled, 4 oz.", 194],
["Fish", "Mackerel, Atlantic, baked, 4 oz.", 297],
["Fish", "Mackerel, Spanish, baked, 4 oz.", 179],
["Fish", "Oysters, canned, 1 cup or 9 oz.", 179],
["Fish", "Oysters, fried, 6 medium, or 3.14 oz.", 173],
["Fish", "Oysters, steamed, 12 medium, or 3 oz.", 117],
["Fish", "Perch, baked, 4 oz.", 132],
["Fish", "Sardines in oil, drained, 3 3/4 oz.—Atlantic", 192],
["Fish", "Sardines, tomato sauce, 3 3/4 oz.", 189],
["Fish", "Scallops, frozen, Mrs. Paul's—3 1/2 oz.", 230],
["Fish", "Scallops, fried, 4 oz. or 7 large scallops", 242],
["Fish", "Scallops, steamed, 4 oz.", 127],
["Fish", "Shad, raw, 4 oz.", 223],
["Fish", "Shark, raw, 4 oz.", 148],
["Fish", "Shrimp, fried, 4 oz.", 275],
["Fish", "Shrimp, fried, frozen, Mrs. Paul's—3 oz.", 200],
["Fish", "Shrimp, steamed, 4 oz.", 112],
["Fish", "Surimi, 4 oz.", 116],
["Fish", "Tuna, bluefin, steamed, 4 oz.", 209],
["Fish", "Tuna, canned in oil, 1 6 1/4 oz. can, drained", 331],
["Fish", "Tuna, canned in water, 1 6 1/4 oz. can", 234],
["Frozen Food", "Almond Chicken, La Choy frozen dinner", 290],
["Frozen Food", "Baby Bay Shrimp, Armour Dinner Classics Lite", 250],
["Frozen Food", "Baked Chicken Breast w/ gravy, Stouffer's frozen dinner", 300],
["Frozen Food", "Barbecue Style Chicken, Stouffer's frozen dinner", 390],
["Frozen Food", "Bean & cheese burrito entree, Old El Paso, each", 340],
["Frozen Food", "Bean & cheese chimichanga, Old El Paso, each", 350],
["Frozen Food", "Beef & bean burrito, hot, Old El Paso, each", 340],
["Frozen Food", "Beef & bean burrito, medium, Old El Paso, each", 330],
["Frozen Food", "Beef & bean burrito, mild, Old El Paso, each", 330],
["Frozen Food", "Beef & Broccoli, La Choy frozen dinner", 290],
["Frozen Food", "Beef & pork chimichanga, Old El Paso, each", 340],
["Frozen Food", "Beef Burgundy with Parsley Noodles, Light & Elegant", 250],
["Frozen Food", "Beef Cannelloni, Lean Cuisine, 9 5/8 oz.", 260],
["Frozen Food", "Beef chimichangas, Old El Paso, each", 380],
["Frozen Food", "Beef Chop Suey with Rice, Stouffer's entree", 300],
["Frozen Food", "Beef Dijon, Stouffer's frozen dinner", 290],
["Frozen Food", "Beef Enchanadas, Lean Cuisine, 9 1/4 oz.", 280],
["Frozen Food", "Beef enchilada, Old El Paso, each", 210],
["Frozen Food", "Beef enchilada dinner, Old El Paso, 11 oz.", 390],
["Frozen Food", "Beef Julienne with rice & pepper, Light & Elegant", 260],
["Frozen Food", "Beef Pepper Steak, Armour Dinner Classics Lite", 290],
["Frozen Food", "Beef pie, Banquet, 1 frozen pot pie", 500],
["Frozen Food", "Beef pie, Morton—7 oz.", 430],
["Frozen Food", "Beef pie, Stouffer's entree", 500],
["Frozen Food", "Beef pot pie, 1 pie—Swanson", 380],
["Frozen Food", "Beef Ragout, Stouffer's frozen dinner", 300],
["Frozen Food", "Beef Short Rib in Gravy, Stouffer entree", 350],
["Frozen Food", "Beef Sirloin Tips, Le Menu frozen dinner", 400],
["Frozen Food", "Beef Stroganoff, Le Menu frozen dinner", 450],
["Frozen Food", "Beef Stroganoff, Armour Dinner Classics", 420],
["Frozen Food", "Beef Stroganoff with Parsley Noodles, Light & Elegant", 290],
["Frozen Food", "Beef Stroganoff with Parsley Noodles, Stouffer entree", 390],
["Frozen Food", "Beef Teriyaki in Sauce, Stouffer entree", 290],
["Frozen Food", "Beef Teriyaki with rice & pea pods, Light & Elegant", 240],
["Frozen Food", "Beef, cheese chimichanga dinner, Old El Paso, 11 oz.", 510],
["Frozen Food", "Beefsteak Ranchero, Lean Cuisine, 9 1/4 oz.", 270],
["Frozen Food", "Breast of Turkey, Le Menu frozen dinner", 270],
["Frozen Food", "Cashew Chicken in Sauce, Stouffer entree", 380],
["Frozen Food", "Cheese Cannelloni, Lean Cuisine, 9 1/8 oz.", 260],
["Frozen Food", "Cheese enchilada, Old El Paso, each", 250],
["Frozen Food", "Cheese enchilada dinner, Old El Paso, 11 oz.", 590],
["Frozen Food", "Cheese enchiladas, Stouffer entree", 590],
["Frozen Food", "Cheese Pizza, Lean Cuisine, French bread", 310],
["Frozen Food", "Cheese Stuffed Shells, Stouffer's frozen dinner", 310],
["Frozen Food", "Chicken & noodles, Armour Dinner Classics", 340],
["Frozen Food", "Chicken a l'Orange, Lean Cuisine, 8 oz.", 260],
["Frozen Food", "Chicken a la King, Le Menu frozen dinner", 330],
["Frozen Food", "Chicken a la King with Rice, Stouffer entree", 290],
["Frozen Food", "Chicken and Vermicelli, Lean Cuisine, 11 3/4 oz.", 270],
["Frozen Food", "Chicken Breast Marsala, Armour Dinner Classics Lite", 270],
["Frozen Food", "Chicken Burgundy, Armour Dinner Classics Lite", 250],
["Frozen Food", "Chicken Cacciatore, Armour Dinner Classics Lite", 240],
["Frozen Food", "Chicken Cacciatore, Lean Cuisine, 10 7/8 oz.", 250],
["Frozen Food", "Chicken chimichangas, Old El Paso, each", 370],
["Frozen Food", "Chicken Chow Mein, Stouffer entree", 130],
["Frozen Food", "Chicken Chow Mein, Lean Cuisine, 11 1/4 oz.", 250],
["Frozen Food", "Chicken Chow Mein, Imperial, La Choy frozen dinner", 270],
["Frozen Food", "Chicken Cordon Bleu, Le Menu frozen dinner", 470],
["Frozen Food", "Chicken Divan, Stouffer entree", 320],
["Frozen Food", "Chicken Enchanadas, Lean Cuisine, 9 7/8 oz.", 270],
["Frozen Food", "Chicken enchilada, Old El Paso, each", 220],
["Frozen Food", "Chicken enchilada with sour cream, Old El Paso, each", 280],
["Frozen Food", "Chicken Enchiladas, Stouffer entree", 490],
["Frozen Food", "Chicken Enchiladas Suiza, Weight Watchers 9.37 oz.", 330],
["Frozen Food", "Chicken Florentine, Stouffer's frozen dinner", 430],
["Frozen Food", "Chicken Florentine, Le Menu frozen dinner", 340],
["Frozen Food", "Chicken fricassee, Armour Dinner Classics", 340],
["Frozen Food", "Chicken in Cheese Sauce, Light & Elegant", 295],
["Frozen Food", "Chicken in Herb, Lean Cuisine, 9 1/2 oz.", 260],
["Frozen Food", "Chicken Italiano, Stouffer's frozen dinner", 280],
["Frozen Food", "Chicken Marsala, Lean Cuisine, 8 1/8 oz.", 190],
["Frozen Food", "Chicken Milan, Armour Dinner Classics", 320],
["Frozen Food", "Chicken Oriental, Armour Dinner Classics Lite", 280],
["Frozen Food", "Chicken Oriental, Lean Cuisine, 9 3/8 oz.", 230],
["Frozen Food", "Chicken Parmesan, Lean Cuisine, 10 oz.", 260],
["Frozen Food", "Chicken Parmigiana, Le Menu frozen dinner", 400],
["Frozen Food", "Chicken Parmigiana, Stouffer's frozen dinner", 360],
["Frozen Food", "Chicken Parmigiana with Parsley, Light & Elegant", 260],
["Frozen Food", "Chicken pie, Banquet, 1 frozen pot pie", 540],
["Frozen Food", "Chicken pie, Stouffer entree", 530],
["Frozen Food", "Chicken pie, Morton—7 oz.", 415],
["Frozen Food", "Chicken pot pie, 1 pie—Swanson", 370],
["Frozen Food", "Chicken Tenderloins, Stouffer's frozen dinner", 330],
["Frozen Food", "Chicken tenderloins in barbecue sauce, Stouffer entree", 270],
["Frozen Food", "Chicken with Supreme Sauce, Stouffer's frozen dinner", 360],
["Frozen Food", "Chicken, Sweet and Sour, Le Menu frozen dinner", 450],
["Frozen Food", "Chili Con Carne with Beans, Stouffer entree", 260],
["Frozen Food", "Chopped Sirloin Beef, Le Menu frozen dinner", 440],
["Frozen Food", "Creamed Chicken, Stouffer entree", 300],
["Frozen Food", "Creamed Chipped Beef, Stouffer entree—11 oz.", 460],
["Frozen Food", "Curry Turkey with Rice, Stouffer's frozen dinner", 320],
["Frozen Food", "Deluxe Pizza, Lean Cuisine, French bread", 350],
["Frozen Food", "Escalloped Chicken & Noodles, Stouffer entree", 420],
["Frozen Food", "Fiesta Beef, Stouffer's frozen dinner", 270],
["Frozen Food", "Fiesta Lasagna, Stouffer entree", 430],
["Frozen Food", "Fillet of Sole, Le Menu frozen dinner", 360],
["Frozen Food", "Fish Divan, Lean Cuisine, 12 3/8 oz.", 260],
["Frozen Food", "Fish Florentine, Lean Cuisine, 9 oz.", 230],
["Frozen Food", "Fish Jardiniere, Lean Cuisine, 11 1/4 oz.", 290],
["Frozen Food", "Fried Chicken, Stouffer's frozen dinner", 450],
["Frozen Food", "Glazed Chicken, Lean Cuisine, 8 1/2 oz.", 270],
["Frozen Food", "Glazed Chicken with Vegetable Rice, Light & Elegant", 240],
["Frozen Food", "Green Pepper Steak with Rice, Stouffer entree", 330],
["Frozen Food", "Ham & Asparagus Bake, Stouffer entree", 510],
["Frozen Food", "Ham Steak, Le Menu frozen dinner", 300],
["Frozen Food", "Homestyle Chicken and Noodles, Stouffer entree", 310],
["Frozen Food", "Homestyle Meatloaf, Stouffer's frozen dinner", 410],
["Frozen Food", "Homestyle Pot Roast, Stouffer's frozen dinner", 220],
["Frozen Food", "Lasagna, Stouffer—10 1/2 oz.", 360],
["Frozen Food", "Lasagna Florentine, Light & Elegant", 280],
["Frozen Food", "Lasagna with Meat, Lean Cuisine, 10 1/4 oz.", 270],
["Frozen Food", "Linguini with Clam, Lean Cuisine, 9 5/8", 270],
["Frozen Food", "Lobster Newburg, Stouffer entree", 380],
["Frozen Food", "Macaroni & Beef w/ Tomatoes, Stouffer—11 1/2 oz.", 340],
["Frozen Food", "Macaroni & Cheese, Stouffer entree—12 oz.", 500],
["Frozen Food", "Macaroni & cheese dinner, Banquet—10 oz.", 415],
["Frozen Food", "Macaroni & Cheese with Bread Crumbs, Light & Elegant", 300],
["Frozen Food", "Manicotti, Le Menu frozen dinner", 360],
["Frozen Food", "Meat Lasagna, Lean Cuisine, 10 1/4 oz.", 270],
["Frozen Food", "Meatball Stew, Lean Cuisine, 10 oz.", 250],
["Frozen Food", "Mincemeat pie, frozen, 1/6 pie, Banquet", 260],
["Frozen Food", "Noodles & chicken dinner, Banquet—10 oz.", 340],
["Frozen Food", "Oriental Beef, Lean Cuisine, 8 5/8 oz.", 250],
["Frozen Food", "Oven Fried Fish, Weight Watchers", 300],
["Frozen Food", "Pasta Mornay with Ham, Lean Cuisine, 9 3/8 oz.", 280],
["Frozen Food", "Pasta Shells, Cheese with Tomato, Stouffer entree", 330],
["Frozen Food", "Pepper Steak, Le Menu frozen dinner", 370],
["Frozen Food", "Pepperoni Pizza, Lean Cuisine, French bread", 340],
["Frozen Food", "Pizza, Extra Cheese, Lean Cuisine, French bread", 350],
["Frozen Food", "Pizza, frozen, individual, 8 oz.", 550],
["Frozen Food", "Rigatoni Bake, Lean Cuisine, 9 3/4 oz.", 260],
["Frozen Food", "Roast Turkey Breast, Stouffer's frozen dinner", 330],
["Frozen Food", "Salisbury Steak, Armour Dinner Classics Lite", 270],
["Frozen Food", "Salisbury Steak, Armour Dinner Classics", 460],
["Frozen Food", "Salisbury Steak, Lean Cuisine, 9 1/2 oz.", 280],
["Frozen Food", "Salisbury Steak in Gravy, Stouffer entree", 250],
["Frozen Food", "Salisbury Steak with Gravy, Stouffer's frozen dinner", 400],
["Frozen Food", "Sausage Pizza, Lean Cuisine, French bread", 350],
["Frozen Food", "Seafood Newburg, Armour Dinner Classics", 300],
["Frozen Food", "Seafood w/ Natural Herbs, Armour Dinner Classics Lite", 220],
["Frozen Food", "Sesame Chicken, Stouffer's frozen dinner", 320],
["Frozen Food", "Shrimp and Chicken, Lean Cuisine, 10 1/8 oz.", 270],
["Frozen Food", "Shrimp Creole dinner, Healthy Choice", 210],
["Frozen Food", "Shrimp Creole with rice & pepper, Light & Elegant", 220],
["Frozen Food", "Shrimp Primavera, Stouffer's frozen dinner", 240],
["Frozen Food", "Shrimp with Lobster Sauce, La Choy frozen dinner", 220],
["Frozen Food", "Sirloin roast, Armour Dinner Classics", 300],
["Frozen Food", "Sirloin tips, Armour Dinner Classics", 340],
["Frozen Food", "Sliced Turkey & Gravy, Light & Elegant", 240],
["Frozen Food", "Sliced Turkey Breast, Lean Cuisine, 8 oz.", 240],
["Frozen Food", "Spaghetti & meatballs dinner, Banquet—10 oz.", 290],
["Frozen Food", "Spaghetti with Beef, Lean Cuisine, 11 1/2 oz.", 280],
["Frozen Food", "Spaghetti with Meat Sauce, Stouffer entree", 370],
["Frozen Food", "Spaghetti with Meat Sauce, Light & Elegant", 290],
["Frozen Food", "Spaghetti with Meatballs, Stouffer entree", 380],
["Frozen Food", "Steak Diane, Armour Dinner Classics Lite", 290],
["Frozen Food", "Stuffed Cabbage, Lean Cuisine, 10 3/4 oz.", 220],
["Frozen Food", "Stuffed Green Peppers with Beef, Stouffer entree", 400],
["Frozen Food", "Stuffed Turkey Breast, Weight Watchers", 260],
["Frozen Food", "Swedish Meatballs in Gravy, Stouffer entree", 480],
["Frozen Food", "Sweet & Sour Chicken, Armour Dinner Classics Lite", 250],
["Frozen Food", "Sweet & Sour Chicken, Healthy Choice frozen dinner", 280],
["Frozen Food", "Szechuan Beef, Lean Cuisine, 9 1/4 oz.", 260],
["Frozen Food", "Taco dinner, 1 taco—Old El Paso", 67],
["Frozen Food", "Tortellini Beef with Marinara, Stouffer entree", 360],
["Frozen Food", "Tortellini Cheese in Alfredo, Stouffer entree", 600],
["Frozen Food", "Tortellini Cheese with Tomato Sauce, Stouffer entree", 360],
["Frozen Food", "Tortellini Cheese with Vinaigret, Stouffer entree", 400],
["Frozen Food", "Tortellini with Meat, Armour Dinner Classics Lite", 250],
["Frozen Food", "Tortilla Grande, Stouffer entree", 530],
["Frozen Food", "Tuna Lasagna, Lean Cuisine, 9 3/4 oz.", 270],
["Frozen Food", "Tuna Noodle Casserole, Stouffer entree", 310],
["Frozen Food", "Tuna pie, Banquet, 1 frozen pot pie", 540],
["Frozen Food", "Turkey & dressing, Armour Dinner Classics", 330],
["Frozen Food", "Turkey Casserole with Gravy, Stouffer entree", 360],
["Frozen Food", "Turkey Dijon, Lean Cuisine, 9 1/2 oz.", 270],
["Frozen Food", "Turkey pie, Banquet, 1 frozen pot pie", 500],
["Frozen Food", "Turkey pie, Morton—7 oz.", 420],
["Frozen Food", "Turkey Pie, Stouffer entree", 540],
["Frozen Food", "Turkey pot pie, 1 pie—Swanson", 390],
["Frozen Food", "Turkey Tetrazzini, Stouffer entree", 380],
["Frozen Food", "Veal Parmigiana, Armour Dinner Classics", 400],
["Frozen Food", "Vegetable Lasagna, Stouffer entree", 420],
["Frozen Food", "Vegetarian Chili, Stouffer's frozen dinner", 280],
["Frozen Food", "Welsh Rarebit, Stouffer entree—10 oz.", 700],
["Frozen Food", "Yankee Pot Roast, Le Menu frozen dinner", 370],
["Frozen Food", "Yankee pot roast, Armour Dinner Classic", 390],
["Frozen Food", "Zucchini Lasagna, Lean Cuisine, 11 oz.", 260],
["Fruit", "Apple, medium, 1 apple, 2 3/4 in., 1/3 lb.", 80],
["Fruit", "Apricot, each", 20],
["Fruit", "Avocado, each", 380],
["Fruit", "Banana, 1 medium—8 3/4 in.", 101],
["Fruit", "Cantaloupe, each", 160],
["Fruit", "Cantaloupe, 1 cup, cubed", 48],
["Fruit", "Grape, each", 2],
["Fruit", "Honeydew melon, 1 cup, cubed", 56],
["Fruit", "Lemon, each", 30],
["Fruit", "Nectarine, 1 2 1/2 in. fruit", 88],
["Fruit", "Orange, Florida, 1 medium orange", 71],
["Fruit", "Orange, navel, 1 medium orange", 71],
["Fruit", "Peach, peeled, medium, 2 1/2 in.", 38],
["Fruit", "Peach, peeled, large, 2 3/4 in.", 58],
["Fruit", "Pear, Bartlett, 1 medium pear, 2 1/2 x 3 1/2 in.", 100],
["Fruit", "Pineapple, sliced, in syrup, 3 in. slice", 43],
["Fruit", "Pineapple, diced, 1 cup", 80],
["Fruit", "Plum, each", 35],
["Fruit", "Plum, Damson, 10 plums, 1 in.", 66],
["Fruit", "Prune, each", 20],
["Fruit", "Raisins, 1 1/2 oz.", 124],
["Fruit", "Strawberries, fresh, 1 cup", 53],
["Fruit", "Strawberries, frozen sliced, 1 cup, with sugar", 278],
["Fruit", "Watermelon, 1 cup", 45],
["Ingredients", "Baking powder, tsp.", 4],
["Ingredients", "Bisquick, 1 cup", 480],
["Ingredients", "Caramel cake icing, 1/12 cake", 64],
["Ingredients", "Chocolate cake icing, 1/12 cake", 104],
["Ingredients", "Chocolate syrup, Hershey's, 1 tbsp.", 40],
["Ingredients", "Corn meal, 1 cup", 502],
["Ingredients", "Corn oil, 1 tbsp.", 122],
["Ingredients", "Cream cheese icing, Pillsbury, 1/12 cake", 160],
["Ingredients", "Flour, 1 cup", 455],
["Ingredients", "Hamburger Helper, Chili, 1 box w/o meat", 520],
["Ingredients", "Hamburger Helper, Lasagna, 1 box, 7 3/4 oz.", 800],
["Ingredients", "Hamburger Helper, Stroganoff, 1 box, w/o meat", 950],
["Ingredients", "Oil, salad, 1 tbsp.", 120],
["Ingredients", "Pepper, black, 1 tsp.", 5],
["Ingredients", "Salt, 1 tbsp.", 0],
["Ingredients", "Tuna Helper, Au gratin, w/o tuna, 1 package", 900],
["Ingredients", "Tuna Helper, Mushroom, w/o tuna, 1 package", 700],
["Ingredients", "Vegetable oil, 1 tbsp.—most varieties", 122],
["Ingredients", "White cake icing, 1/12 cake", 100],
["Ingredients", "Whole wheat flour, 1 cup", 400],
["Juice", "Apple juice, 1 cup", 117],
["Juice", "Grapefruit juice, 1 cup", 96],
["Juice", "Hi-C, 8 fl. oz.", 133],
["Juice", "Orange juice, fresh, 8 fl. oz.", 112],
["Juice", "Orange juice, frozen reconstituted, 8 fl. oz.", 122],
["Juice", "Tomato juice, 6 fl. oz.", 30],
["Juice", "V8 Juice, regular or spicy, 6 fl. oz.", 35],
["Kentucky Fried Chicken", "Barbecue sauce, 1 oz.", 35],
["Kentucky Fried Chicken", "Biscuit, each", 235],
["Kentucky Fried Chicken", "Chicken breast, center, extra crispy", 342],
["Kentucky Fried Chicken", "Chicken breast, center, original recipe", 283],
["Kentucky Fried Chicken", "Chicken breast, side, original recipe", 267],
["Kentucky Fried Chicken", "Chicken breast, side, extra crispy", 343],
["Kentucky Fried Chicken", "Chicken drumstick, original recipe", 146],
["Kentucky Fried Chicken", "Chicken drumstick, extra crispy", 204],
["Kentucky Fried Chicken", "Chicken Littles, each", 169],
["Kentucky Fried Chicken", "Chicken sandwich, each", 482],
["Kentucky Fried Chicken", "Chicken thigh, original recipe", 294],
["Kentucky Fried Chicken", "Chicken thigh, extra crispy", 406],
["Kentucky Fried Chicken", "Chicken wing, original recipe", 178],
["Kentucky Fried Chicken", "Chicken wing, extra crispy", 254],
["Kentucky Fried Chicken", "Coleslaw, 1 serving", 119],
["Kentucky Fried Chicken", "Corn on the cob, 1 serving, 5 oz.", 176],
["Kentucky Fried Chicken", "French fries, 1 serving", 244],
["Kentucky Fried Chicken", "Honey sauce, 1 oz.", 49],
["Kentucky Fried Chicken", "Kentucky nuggets, 1 nugget", 46],
["Kentucky Fried Chicken", "Mashed potatoes, 1 serving with gravy", 71],
["Kentucky Fried Chicken", "Mustard sauce, 1 oz.", 36],
["Kentucky Fried Chicken", "Sweet'n'sour sauce, 1 oz.", 58],
["McDonald's", "1000 Island dressing, 1 package", 390],
["McDonald's", "Apple pie, each", 260],
["McDonald's", "Big Mac, each", 560],
["McDonald's", "Bleu Cheese dressing, 1 package", 350],
["McDonald's", "Caesar dressing, 1 package", 300],
["McDonald's", "Cheeseburger, each", 310],
["McDonald's", "Chef salad, each", 230],
["McDonald's", "Chicken McNuggets, 1 nugget", 48],
["McDonald's", "Chicken salad, each", 140],
["McDonald's", "Chocolate chip cookies, 1 box", 330],
["McDonald's", "Chocolate milkshake, 1 milkshake—10.3 fl. oz.", 390],
["McDonald's", "Egg McMuffin, each", 330],
["McDonald's", "Filet-O-Fish, each", 432],
["McDonald's", "French dressing, 1 package", 230],
["McDonald's", "French fries, small serving", 220],
["McDonald's", "French fries, medium serving", 320],
["McDonald's", "French fries, large serving", 400],
["McDonald's", "Garden salad, 1 salad", 110],
["McDonald's", "Hamburger, each", 260],
["McDonald's", "Hash browns, each", 130],
["McDonald's", "Ice cream, soft serve cone", 140],
["McDonald's", "McDonaldland cookies, box", 290],
["McDonald's", "McNuggets barbecue sauce, 1.1 oz.", 50],
["McDonald's", "McNuggets mustard sauce, 1 serving", 70],
["McDonald's", "McNuggets sweet & sour sauce, 1 serving", 60],
["McDonald's", "Peppercorn dressing, 1 package", 400],
["McDonald's", "Quarter Pounder, each", 410],
["McDonald's", "Quarter Pounder with cheese, each", 520],
["McDonald's", "Ranch dressing, 1 package", 330],
["McDonald's", "Red French dressing, 1 package", 160],
["McDonald's", "Sausage biscuit, 1 biscuit & patty", 440],
["McDonald's", "Side salad, 1 salad", 60],
["McDonald's", "Strawberry milkshake, 1 milkshake—10.3 fl. oz.", 380],
["McDonald's", "Sundae, hot caramel, each", 340],
["McDonald's", "Sundae, hot fudge, each", 310],
["McDonald's", "Sundae, strawberry, each", 280],
["McDonald's", "Thousand Island Dressing, 1 package—2 oz.", 390],
["McDonald's", "Vanilla milkshake, 1 milkshake—10.3 fl. oz.", 350],
["McDonald's", "Vinaigrette dressing, 1 package", 60],
["Meat", "Bacon, 1 slice, 20/lb.", 36],
["Meat", "Beef bofoodna, 1 slice, 1 oz.", 89],
["Meat", "Beef salami, 1 slice, 0.8 oz.", 58],
["Meat", "Beef stew, 8 oz.—Dinty Moore", 220],
["Meat", "Beef, chuck roast, 4 oz., lean", 265],
["Meat", "Beef, flank steak, 4 oz., broiled", 288],
["Meat", "Beef, ground, cooked, 4 oz., extra lean", 288],
["Meat", "Beef, ground, cooked, 4 oz., regular", 347],
["Meat", "Beef, ground, raw, 4 oz., extra lean", 265],
["Meat", "Beef, ground, raw, 4 oz., lean", 298],
["Meat", "Beef, ground, raw, 4 oz., regular", 351],
["Meat", "Beef, porterhouse steak, 4 oz., broiled", 247],
["Meat", "Beef, round roast, 4 oz., lean", 208],
["Meat", "Beef, sirloin steak, 4 oz., broiled", 240],
["Meat", "Beef, T-bone steak, 4 oz., broiled, lean", 243],
["Meat", "Breakfast sausage, link, 1 link, 1 oz. raw", 48],
["Meat", "Breakfast sausage, patty, 1 patty, 3 7/8 in.", 100],
["Meat", "Chili con carne, 15 1/2 oz. can", 572],
["Meat", "Corned beef brisket, 4 oz.", 284],
["Meat", "Corned beef, canned, 1 oz.", 71],
["Meat", "Country ham, 4 oz., lean", 220],
["Meat", "Ham, canned, 4 oz., unheated", 164],
["Meat", "Ham, cooked smoked, 1 slice—Oscar Mayer", 20],
["Meat", "Ham, extra lean, 4 oz.", 164],
["Meat", "Ham, picnic, 4 oz.", 177],
["Meat", "Ham, regular, 4 oz., lean", 201],
["Meat", "Ham, sliced, 1 slice, 1 oz.", 52],
["Meat", "Hot dog, beef, 1 hot dog, 8 per pound", 184],
["Meat", "Hot dog, pork and beef, 1 hot dog, 8 per pound", 183],
["Meat", "Italian sausage, 1 link, 1/4 pound", 268],
["Meat", "Little smoked sausage, 1 link", 43],
["Meat", "Liverwurst, 1 oz.", 93],
["Meat", "Luncheon meat, beef, 1 slice, 1 oz.", 87],
["Meat", "Peppered sandwich loaf, pork, beef, 1 slice, 1 oz.", 42],
["Meat", "Pepperoni, 1 oz., 14 slices, Hormel", 140],
["Meat", "Pork and beans, 1 cup", 311],
["Meat", "Pork and beans, 1 can, 20 oz.", 692],
["Meat", "Pork center rib, 1 chop, 3 oz., pan-fried", 219],
["Meat", "Pork loin roast, 4 oz., lean", 268],
["Meat", "Pork spareribs, 4 oz., braised", 451],
["Meat", "Pork, Boston butt roast, 4 oz., lean", 291],
["Meat", "Pork, loin chop, trimmed, broiled, 1 3 oz. chop", 294],
["Meat", "Ravioli, Mini, Chef Boyardee, 1 can", 420],
["Meat", "Spam, 2 oz.", 170],
["Meat", "Venison, 4 oz., lean", 143],
["Nuts", "Almonds, dry roasted, smoke flavor Planters, 1 oz.", 170],
["Nuts", "Almonds, slivered, Planter's 1/3 cup, 2 oz.", 170],
["Nuts", "English walnuts, 10 nuts", 322],
["Nuts", "English walnuts, 1 cup, chopped", 781],
["Nuts", "Peanut butter, 1 tbsp.", 94],
["Nuts", "Peanuts, honey roasted, Planters, 1 oz.", 170],
["Nuts", "Peanuts, roasted in shell, 10 peanuts", 105],
["Nuts", "Peanuts, roasted, canned, 1 oz.", 170],
["Nuts", "Peanuts, salted, Lance, 1 1/8 oz.", 190],
["Nuts", "Pecans, 1 cup shelled halves", 742],
["Nuts", "Sunflower seeds, raw, unsalted, 1 oz.", 159],
["Nuts", "Sunflower seeds, roasted, Planters, 1 oz.", 160],
["Pasta", "Egg noodles, 1 cup", 200],
["Pasta", "Fried noodles, 1 cup", 220],
["Pasta", "Macaroni & cheese, baked, home recipe, 1 cup", 430],
["Pasta", "Macaroni & cheese, mix, Kraft—1 cup, per directions", 386],
["Pasta", "Macaroni, firm, 1 cup", 192],
["Pasta", "Macaroni, tender, 1 cup", 155],
["Pasta", "Spaghetti, al dente, 1 cup", 192],
["Pasta", "Spaghetti, tender, 1 cup", 155],
["Pasta", "Suddenly Salad Classic Pasta, Betty Crocker—1 box", 960],
["Pizza Hut", "Cheese, 1 slice—Thin 'n Crispy", 149],
["Pizza Hut", "Cheese, 1 slice—pan pizza", 246],
["Pizza Hut", "Cheese, 1 slice—Hand Tossed", 259],
["Pizza Hut", "Pepperoni, 1 slice—Thin 'n Crispy", 207],
["Pizza Hut", "Pepperoni, 1 slice—Hand Tossed", 250],
["Pizza Hut", "Pepperoni, 1 slice—pan pizza", 270],
["Pizza Hut", "Pepperoni, 1 pizza—Personal Pan", 675],
["Pizza Hut", "Super Supreme, 1 slice—Thin 'n Crispy", 232],
["Pizza Hut", "Super Supreme, 1 slice—pan pizza", 266],
["Pizza Hut", "Super Supreme, 1 slice—Hand Tossed", 278],
["Pizza Hut", "Supreme, 1 slice—Thin 'n Crispy", 230],
["Pizza Hut", "Supreme, 1 slice—Hand Tossed", 270],
["Pizza Hut", "Supreme, 1 slice—pan pizza", 290],
["Pizza Hut", "Supreme, 1 pizza—Personal Pan", 647],
["Poultry", "Chicken back, fried, w/o skin, 1/2 back", 167],
["Poultry", "Chicken back, fried, with skin, 1/2 back", 238],
["Poultry", "Chicken back, roasted, w/o skin, 1/2 back", 96],
["Poultry", "Chicken back, roasted, with skin, 1/2 back", 159],
["Poultry", "Chicken breast, fried, w/o skin, 1/2 breast", 161],
["Poultry", "Chicken breast, fried, with skin, 1/2 breast", 218],
["Poultry", "Chicken breast, roasted, w/o skin, 1/2 breast", 142],
["Poultry", "Chicken breast, roasted, with skin, 1/2 breast", 193],
["Poultry", "Chicken breast, smoked, Butterball, 1 slice", 30],
["Poultry", "Chicken drumstick, fried, w/o skin, 1 drumstick", 82],
["Poultry", "Chicken drumstick, fried, with skin, 1 drumstick", 120],
["Poultry", "Chicken drumstick, roasted, w/o skin", 76],
["Poultry", "Chicken drumstick, roasted, with skin", 112],
["Poultry", "Chicken giblets, fried, 1 cup or 5 oz.", 402],
["Poultry", "Chicken hot dog, 1 hot dog, 10 per pound", 116],
["Poultry", "Chicken livers, simmered, 1 cup or 5 oz. or 7 livers", 219],
["Poultry", "Chicken neck, fried, w/o skin, 1 neck", 50],
["Poultry", "Chicken neck, fried, with skin, 1 neck", 119],
["Poultry", "Chicken neck, simmered, w/o skin", 32],
["Poultry", "Chicken neck, simmered, with skin", 94],
["Poultry", "Chicken thigh, fried, w/o skin, 1 thigh", 113],
["Poultry", "Chicken thigh, fried, with skin, 1 thigh", 162],
["Poultry", "Chicken thigh, roasted, w/o skin", 109],
["Poultry", "Chicken thigh, roasted, with skin", 153],
["Poultry", "Chicken wing, fried, w/o skin, 1 wing", 42],
["Poultry", "Chicken wing, fried, with skin, 1 wing", 103],
["Poultry", "Chicken wing, roasted, w/o skin", 43],
["Poultry", "Chicken wing, roasted, with skin", 99],
["Poultry", "Chicken, dark meat, fried, 1 cup, or 5 oz. w/o skin", 334],
["Poultry", "Chicken, dark meat, roasted, 1 cup or 5 oz., w/o skin", 250],
["Poultry", "Chicken, light meat, fried, 1 cup, or 5 oz., w/o skin", 268],
["Poultry", "Chicken, light meat, roasted, 1 cup or 5 oz., w/o skin", 214],
["Poultry", "Duck, roasted, w/o skin, 4 oz.", 228],
["Poultry", "Duck, roasted, with skin, 4 oz.", 382],
["Poultry", "Goose liver, raw, 4 oz.", 151],
["Poultry", "Goose, roasted, w/o skin, 4 oz.", 270],
["Poultry", "Pheasant, raw, w/o skin, 4 oz.", 151],
["Poultry", "Quail, raw, w/o skin, 4 oz.", 152],
["Poultry", "Turkey bofoodna, 1 slice—average", 57],
["Poultry", "Turkey bofoodna, 1 slice—Butterball", 70],
["Poultry", "Turkey ham, 1 slice—Louis Rich", 35],
["Poultry", "Turkey hot dog, 1 hot dog, 10 per pound", 102],
["Poultry", "Turkey kielbasa, 4 oz.—Louis Rich", 160],
["Poultry", "Turkey loaf, sliced, 2 slices, 1 1/2 oz.", 47],
["Poultry", "Turkey pastrami, 1 slice, Louis Rich", 35],
["Poultry", "Turkey sausage, Louis Rich—4 oz.", 160],
["Poultry", "Turkey, raw, average, 4 oz., w/o skin", 135],
["Poultry", "Turkey, roasted, 1 cup, or 5 oz.", 238],
["Salad", "Bac O's, 1 tbsp", 40],
["Salad", "Blue cheese dressing, 1 tbsp.", 80],
["Salad", "French dressing, 1 tbsp.", 60],
["Salad", "Italian dressing, 1 tbsp.", 70],
["Salad", "Potato salad with egg, home recipe, 1 cup", 363],
["Salad", "Thousand island dressing, 1 tbsp.", 70],
["Salad", "Three bean salad, Green Giant, 1 cup", 140],
["Salad", "Tuna salad, home recipe, 1 cup", 349],
["Sauces", "Au jus gravy mix, with water, 1 cup", 19],
["Sauces", "Barbecue sauce, 1 tbsp.—Hunt's", 20],
["Sauces", "Brown gravy mix, with water, 1 cup", 9],
["Sauces", "Catsup, 1 tbsp.", 18],
["Sauces", "Chicken gravy mix, with water, 1 cup", 83],
["Sauces", "Enchilada sauce, hot, 1 cup—Old El Paso", 120],
["Sauces", "Enchilada sauce, mild, 1 cup—Old El Paso", 100],
["Sauces", "Mayonnaise, 1 tbsp.", 100],
["Sauces", "Mayonnaise, 1 cup", 1577],
["Sauces", "Mayonnaise, Weight Watchers, 1 tbsp.", 50],
["Sauces", "Miracle Whip, 1 tbsp.", 70],
["Sauces", "Miracle Whip Light, 1 tbsp.", 45],
["Sauces", "Mushroom gravy mix, with water, 1 cup", 70],
["Sauces", "Mustard, brown, 1 tsp.", 5],
["Sauces", "Mustard, yellow, 1 tbsp.", 10],
["Sauces", "Pizza Quick sauce, Ragu, 3 tbsp.", 35],
["Sauces", "Soy sauce, 1 tbsp.", 12],
["Sauces", "Spaghetti sauce, basil, 1 cup—Classico", 100],
["Sauces", "Spaghetti sauce, beef-pork, 1 cup—Classico", 140],
["Sauces", "Spaghetti sauce, mushroom, 1 cup—Classico", 140],
["Sauces", "Spaghetti sauce, Newman's own, 1 cup", 140],
["Sauces", "Spaghetti sauce, Ragu, Homestyle, 1 cup", 100],
["Sauces", "Spaghetti sauce, Ragu, Chunky Gardenstyle, 1 cup", 140],
["Sauces", "Spaghetti sauce, Ragu, 1 cup", 160],
["Sauces", "Spaghetti sauce, Ragu, Fresh Italian, 1 cup", 180],
["Sauces", "Spaghetti sauce, Ragu, Thick & Hearty, 1 cup", 200],
["Sauces", "Taco sauce, 1 tbsp.—Old El Paso", 5],
["Sauces", "Taco seasoning mix, 1 package—Old El Paso", 100],
["Sauces", "Thick n Chunky Salsa, 1 tbsp.—Old El Paso", 3],
["Sauces", "Vinegar, 1 fl. oz.", 4],
["Sauces", "Vinegar, cider, 1 cup", 34],
["Sauces", "Vinegar, distilled, 1 cup", 29],
["Sauces", "White sauce mix, with milk, 1 cup", 241],
["Sauces", "Worcestershire sauce, 1 tbsp.", 15],
["Snacks", "Canned onion rings, 1 2.8 oz. can—Durkee", 480],
["Snacks", "Chee-tos, 1 oz.—25 chips", 150],
["Snacks", "Doritos, 1 oz.", 140],
["Snacks", "Fritos, 1 oz.", 150],
["Snacks", "Popcorn, air-popped, 1 cup", 25],
["Snacks", "Popcorn, microwave, Newman's Own, 8 cups", 360],
["Snacks", "Popcorn, microwave, Golden Valley—1 bag, 8 cups", 374],
["Snacks", "Popcorn, microwave, light, Orville Redenbacher—1 bag", 234],
["Snacks", "Popcorn, with oil & salt, 1 cup", 41],
["Snacks", "Potato chips, Lay's—1 oz.", 150],
["Snacks", "Pretzel sticks, 1 oz.", 111],
["Snacks", "Pretzels, 3-ring, 10 pretzels", 117],
["Snacks", "Pringles corn chips, 1 can, 6 oz.", 840],
["Snacks", "Tortilla chips, 1 oz.—Old El Paso", 150],
["Soup", "Bean with bacon soup, 1 can—Campbell's", 431],
["Soup", "Beef broth, Campbell's—1 can", 40],
["Soup", "Chicken noodle soup, 1 can—Campbell's", 140],
["Soup", "Chicken with rice soup, 1 can—Campbell's", 150],
["Soup", "Chicken with stars soup, 1 can—Campbell's", 150],
["Soup", "Chili beef soup, 1 can—Campbell's", 385],
["Soup", "Cream of chicken soup, 1 can—Campbell's", 307],
["Soup", "Cream of mushroom soup, 1 can—Campbell's", 275],
["Soup", "Cream of potato soup, 1 can—Campbell's", 311],
["Soup", "French onion soup, 1 can—Campbell's", 150],
["Soup", "Golden mushroom soup, 1 can—Campbell's", 220],
["Soup", "Hot and sour soup, 1 cup", 100],
["Soup", "Meatball vegetable soup, 1 can—Campbell's", 275],
["Soup", "Split pea soup, 1 can—Campbell's", 450],
["Soup", "Tomato soup, 1 can—Campbell's", 247],
["Soup", "Vegetable beef soup, 1 can—Campbell's", 175],
["Soup", "Vegetable soup, 1 can—Campbell's", 225],
["Soup", "Wonton soup, 1 cup", 210],
["Sugar", "Blackstrap molasses, 1 tbsp.", 43],
["Sugar", "Blackstrap molasses, 1 cup", 699],
["Sugar", "Honey, 1 tbsp.", 64],
["Sugar", "Jam, 1 tbsp.", 54],
["Sugar", "Jelly, 1 tsp.", 18],
["Sugar", "Jelly, 1 tbsp.", 49],
["Sugar", "Maple syrup, Aunt Jemima, 1 fl. oz.", 102],
["Sugar", "Maple syrup, Aunt Jemima Lite, 1 fl. oz.", 58],
["Sugar", "Sugar, 1 tsp.", 15],
["Sugar", "Sugar, 1 tbsp.", 46],
["Sugar", "Sugar, 1 cup", 770],
["Taco Bell", "Bean burrito, green sauce", 351],
["Taco Bell", "Bean burrito, red sauce", 357],
["Taco Bell", "Beef burrito, green sauce", 398],
["Taco Bell", "Beef burrito, red sauce", 403],
["Taco Bell", "Burrito supreme, green sauce", 407],
["Taco Bell", "Burrito supreme, red sauce", 413],
["Taco Bell", "Enchirito, green sauce", 371],
["Taco Bell", "Enchirito, red sauce", 382],
["Taco Bell", "Guacamole sauce, 1 serving", 34],
["Taco Bell", "Soft taco, each", 228],
["Taco Bell", "Taco, regular taco", 183],
["Taco Bell", "Taco Bellgrande, each", 355],
["Taco Bell", "Taco light, each", 410],
["Taco Bell", "Tostada, green sauce", 237],
["Taco Bell", "Tostada, red sauce", 243],
["Vegetables", "Artichokes, 1 artichoke", 67],
["Vegetables", "Asparagus, canned, 1 10 1/2 oz. can", 54],
["Vegetables", "Asparagus, fresh, 1 cup, boiled", 36],
["Vegetables", "Baked beans, 1 cup, canned, w/o pork", 306],
["Vegetables", "Bean curd, 4 oz.", 81],
["Vegetables", "Bean sprouts, boiled, 1 cup", 35],
["Vegetables", "Bean sprouts, raw, 1 cup", 37],
["Vegetables", "Beets, 1 cup, fresh", 54],
["Vegetables", "Beets, canned, 1 can, 10 1/2 oz.", 109],
["Vegetables", "Blackeye peas, 1 cup", 178],
["Vegetables", "Broccoli, cooked, 1 cup", 40],
["Vegetables", "Brussel sprouts, 1 cup, fresh", 56],
["Vegetables", "Butternut squash, baked—1 cup", 139],
["Vegetables", "Cabbage, cooked, 1 cup", 31],
["Vegetables", "Cabbage, raw, shredded, 1 cup", 17],
["Vegetables", "Carrot, raw, 1 carrot", 30],
["Vegetables", "Carrots, cooked, 1 cup", 45],
["Vegetables", "Carrots, sliced, 1 cup", 48],
["Vegetables", "Cauliflower, boiled, 1 cup", 28],
["Vegetables", "Cauliflower, raw, 1 cup, chopped", 31],
["Vegetables", "Celery, 3 small stalks, 5 in.", 9],
["Vegetables", "Chard, fresh, 1 cup", 32],
["Vegetables", "Coleslaw with French dressing, 1 cup", 114],
["Vegetables", "Coleslaw with salad dressing, 1 cup", 119],
["Vegetables", "Collards, canned, 1 cup", 51],
["Vegetables", "Collards, fresh, 1 cup", 42],
["Vegetables", "Corn on the cob, 1 5 in. ear", 70],
["Vegetables", "Corn, canned whole kernel, 1 can—10 oz.", 360],
["Vegetables", "Corn, cooked, 1 cup", 140],
["Vegetables", "Corn, creamed, 1 can, 15 1/2 oz.", 320],
["Vegetables", "Cucumbers, each", 30],
["Vegetables", "Eggplant, 1 cup, boiled", 38],
["Vegetables", "Eggplant sticks, fried, Mrs. Paul's, 3 1/2 oz.", 240],
["Vegetables", "Garbanzos, dry, 1 cup", 367],
["Vegetables", "Garden medley, Green Giant, 1 can—beans, carrots, corn", 158],
["Vegetables", "Garlic, raw, 1 clove", 4],
["Vegetables", "Great northern beans, 1 cup", 212],
["Vegetables", "Green beans, boiled, 1 cup", 31],
["Vegetables", "Green beans, canned, Del Monte, 1 16 oz. can", 80],
["Vegetables", "Green beans, low sodium, Del Monte, 1 16 oz. can", 80],
["Vegetables", "Green pepper, 1 pepper, 1/5 pound", 16],
["Vegetables", "Green pepper, diced, 1 cup", 33],
["Vegetables", "Grits, Quaker, 1 cup", 133],
["Vegetables", "Hotdog relish, 1 oz., Vlasic", 40],
["Vegetables", "Kale, fresh, 1 cup", 43],
["Vegetables", "Kale, frozen, 1 cup", 40],
["Vegetables", "Kidney beans, canned, 1 cup", 230],
["Vegetables", "Kidney beans, dried, 1 cup, cooked", 218],
["Vegetables", "Lentils, 1 cup", 212],
["Vegetables", "Lettuce, iceberg, 1 cup, shredded", 7],
["Vegetables", "Lettuce, iceberg, 1 head", 70],
["Vegetables", "Lima beans, 1 cup", 189],
["Vegetables", "Mushrooms, 1 cup, chopped", 20],
["Vegetables", "Mustard greens, fresh, 1 cup", 32],
["Vegetables", "Mustard greens, frozen, 1 cup", 30],
["Vegetables", "Navy beans, 1 cup", 224],
["Vegetables", "Okra, fried, 3 oz., Ore-Ida", 170],
["Vegetables", "Olives, green, 10 large", 45],
["Vegetables", "Olives, ripe, 10 extra large", 61],
["Vegetables", "Onions, raw, 1 cup", 65],
["Vegetables", "Peas, cooked, 1 cup", 115],
["Vegetables", "Pickles, dill, 1 pickle—3 3/4 x 1 1/4 in.", 7],
["Vegetables", "Pickles, dill, 1 oz.", 4],
["Vegetables", "Pickles, sweet, 1 oz.", 30],
["Vegetables", "Pinto beans, 1 cup", 228],
["Vegetables", "Potato, baked, 2 1/3 x 4 3/4 in.", 145],
["Vegetables", "Potato, boiled, medium, pared, 2 1/2 in.", 88],
["Vegetables", "Potato, boiled, large, pared, 2.3 x 4.7 in.", 146],
["Vegetables", "Potato, french fries, 3 oz.", 130],
["Vegetables", "Potato, frozen french fries, Golden Crinkles 3 oz.", 120],
["Vegetables", "Potato, frozen hash browns, Golden Patties 2 1/2 oz.", 140],
["Vegetables", "Potato, microwave hash browns, Ore-Ida, 2 oz.", 120],
["Vegetables", "Potatoes, mashed instant, from flakes, 1 cup", 195],
["Vegetables", "Potatoes, mashed with milk, 1 cup", 137],
["Vegetables", "Radish, 10 medium radishes", 8],
["Vegetables", "Radish, 1 cup sliced", 20],
["Vegetables", "Refried beans, 1 cup—Old El Paso", 200],
["Vegetables", "Refried beans with green chili, 1 cup—Old El Paso", 200],
["Vegetables", "Refried beans with sausage, 1 cup—Old El Paso", 720],
["Vegetables", "Rice a Roni, wild rice—1/4 box", 110],
["Vegetables", "Rice pilaf, Green Giant—1 cup", 220],
["Vegetables", "Rice, brown, 1 cup, cooked", 232],
["Vegetables", "Rice, fried, 1 cup", 418],
["Vegetables", "Rice, instant, 1 cup, cooked", 180],
["Vegetables", "Rice, white, 1 cup, cooked", 223],
["Vegetables", "Sauerkraut, canned, 1 cup", 42],
["Vegetables", "Snow peas, 1 package, LaChoy", 70],
["Vegetables", "Spinach, fresh, 1 cup", 14],
["Vegetables", "Spinach, frozen, 1 cup", 46],
["Vegetables", "Squash, 1 cup", 30],
["Vegetables", "Sugar snap peas, Green Giant, 1 cup", 50],
["Vegetables", "Sweet potatoes, canned, 1 cup", 216],
["Vegetables", "Sweet potatoes, fresh, 5 x 2 in., boiled", 172],
["Vegetables", "Tater Tots, 3 oz.—Ore Ida", 150],
["Vegetables", "Tofu, 4 oz.", 81],
["Vegetables", "Tomato, raw, 1 tomato", 26],
["Vegetables", "Tomatoes, canned, 1 can—16 oz.", 95],
["Vegetables", "Turnip greens, canned, 1 cup", 42],
["Vegetables", "Turnip greens, fresh, 1 cup", 29],
["Vegetables", "Turnip greens, frozen, 1 cup", 38],
["Vegetables", "Watermelon, 1 cup", 42],
["Vegetables", "Zucchini, 1 cup", 22],
["Wendy's", "Big Classic, each", 470],
["Wendy's", "Chicken filet, each", 200],
["Wendy's", "French fries, 1 serving", 300],
["Wendy's", "Frosty, small", 400],
["Wendy's", "Single, each", 350]
]

def extract_import_group_names
  foods = FOODS
  i = 0
  while i <= foods.size do 
    foods.each do |food|
      group_name = food[i]
      group_name = Group.find_or_create_by(name: group_name)
      i += 1
    end
  end
end

extract_import_group_names
 